script: . ./ci.sh

branches:
  only:
    - master

matrix:
  fast_finish: true
  include:
  - env: SUITE="go"
    language: go
    go: 1.8
  - env: SUITE="js" CXX=clang
    language: node_js
    node_js: 7
  - env: SUITE="js" CXX=clang
    language: node_js
    node_js: 8
  - env: SUITE="python"
    language: python
    python: 2.7
  - env: SUITE="python"
    language: python
    python: 3.6
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.4.1
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.3.3
  - env: SUITE="ruby"
    language: ruby
    rvm: 2.2.2
  - env: SUITE="rust"
    language: rust
    rust: stable
  - env: SUITE="rust"
    language: rust
    rust: nightly

compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6
